"""add agent inference params and description

Revision ID: 5dd68e90d6f0
Revises: c4d5e6f7a8b9
Create Date: 2026-07-11 13:19:20.033616+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd68e90d6f0'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('agents', sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False))
    op.add_column('agents', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('top_p', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'top_p')
    op.drop_column('agents', 'max_tokens')
    op.drop_column('agents', 'temperature')
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
