"""add groups and group_tenants tables

Revision ID: 574391d912fc
Revises: 5dd68e90d6f0
Create Date: 2026-07-12 04:31:28.054492+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574391d912fc'
down_revision: Union[str, Sequence[str], None] = '5dd68e90d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_is_deleted'), 'groups', ['is_deleted'], unique=False)
    op.create_index('uq_groups_code_active', 'groups', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = 0'))
    op.create_table('group_tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'tenant_id', name='uq_group_tenant')
    )
    op.create_index('idx_group_tenants_tenant_id', 'group_tenants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_tenants_tenant_id', table_name='group_tenants')
    op.drop_table('group_tenants')
    op.drop_index('uq_groups_code_active', table_name='groups', postgresql_where=sa.text('is_deleted = false'), sqlite_where=sa.text('is_deleted = 0'))
    op.drop_index(op.f('ix_groups_is_deleted'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
