"""add tenant status/created_by/description/address

Revision ID: 84605f063730
Revises: 6f197cf8f964
Create Date: 2026-07-12 12:49:03.238148+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84605f063730'
down_revision: Union[str, Sequence[str], None] = '6f197cf8f964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # status is NOT NULL; backfill existing rows with 'active' (matches the
    # model default) before adding the constraint.
    op.add_column(
        'tenants',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='active'),
    )
    op.add_column('tenants', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('created_by', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'status')
    # ### end Alembic commands ###
